repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Run the linter on changed files only
      - id: ruff
        args: [--fix]
      # Run the formatter on changed files only
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: ./scripts/mypy.sh
        language: system
        pass_filenames: false
        files: ^(apps/discord_bot/src/five08/|apps/worker/src/five08/|packages/shared/src/five08/)
